python run.py keyboard data/*
python run.py kleenex data/*
python run.py lemon data/*
python run.py lightbulb data/*
python run.py lime data/*
python run.py marker data/*
python run.py mushroom data/*
python run.py notebook data/*
python run.py onion data/*
python run.py orange data/*
python run.py peach data/*
python run.py pear data/*
python run.py pitcher data/*
