python run.py plate data/*
python run.py pliers data/*
python run.py potato data/*
python run.py rubber_eraser data/*
python run.py scissors data/*
python run.py shampoo data/*
python run.py soda_can data/*
python run.py sponge data/*
python run.py stapler data/*
python run.py tomato data/*
python run.py toothbrush data/*
python run.py toothpaste data/*
python run.py water_bottle data/*
