python run.py comb data/*
python run.py dry_battery data/*
python run.py flashlight data/*
python run.py food_bag data/*
python run.py food_box data/*
python run.py food_can data/*
python run.py food_cup data/*
python run.py food_jar data/*
python run.py garlic data/*
python run.py glue_stick data/*
python run.py greens data/*
python run.py hand_towel data/*
python run.py instant_noodles data/*
