python run.py apple data/*
python run.py ball data/*
python run.py banana data/*
python run.py bell_pepper data/*
python run.py binder data/*
python run.py bowl data/*
python run.py calculator data/*
python run.py camera data/*
python run.py cap data/*
python run.py cell_phone data/*
python run.py cereal_box data/*
python run.py coffee_mug data/*
